### ISSUE TITLE
Unexpected behavior with tomcat 8.0.36 setup

### ISSUE THREAD

**Issue by andreptb** [grgrzybek/tomcat-slf4j-logback#112] opened 2016-07-28 21:01 UTC
Hi @grgrzybek ,

I'm having a hard time setting up tomcat 8.0.36 with logback. I've followed the procedure described in _README.md_ but I'm not getting the desired results.

After starting tomcat with _$CATALINA_HOME/bin/startup.sh_ the logging files configured in logback.xml appenders are not being created in $CATALINA_HOME/logs. Furthermore, a file named _$CATALINA_HOME/logs/catalina.out_ is being created. Below the first 10 lines generated:

```
17:49:14.128 [main] DEBUG org.apache.catalina.startup.ClassLoaderFactory - Creating new class loader
17:49:14.130 [main] DEBUG org.apache.catalina.startup.ClassLoaderFactory -   Including directory file:/home/andre/dev/tmp/apache-tomcat-8.0.36/lib/
17:49:14.131 [main] DEBUG org.apache.catalina.startup.ClassLoaderFactory -   Including directory glob /home/andre/dev/tmp/apache-tomcat-8.0.36/lib
17:49:14.131 [main] DEBUG org.apache.catalina.startup.ClassLoaderFactory -     Including glob jar file /home/andre/dev/tmp/apache-tomcat-8.0.36/lib/jasper.jar
17:49:14.131 [main] DEBUG org.apache.catalina.startup.ClassLoaderFactory -     Including glob jar file /home/andre/dev/tmp/apache-tomcat-8.0.36/lib/catalina-storeconfig.jar
17:49:14.131 [main] DEBUG org.apache.catalina.startup.ClassLoaderFactory -     Including glob jar file /home/andre/dev/tmp/apache-tomcat-8.0.36/lib/tomcat-i18n-ja.jar
17:49:14.131 [main] DEBUG org.apache.catalina.startup.ClassLoaderFactory -     Including glob jar file /home/andre/dev/tmp/apache-tomcat-8.0.36/lib/tomcat-i18n-es.jar
17:49:14.131 [main] DEBUG org.apache.catalina.startup.ClassLoaderFactory -     Including glob jar file /home/andre/dev/tmp/apache-tomcat-8.0.36/lib/tomcat-util.jar
17:49:14.132 [main] DEBUG org.apache.catalina.startup.ClassLoaderFactory -     Including glob jar file /home/andre/dev/tmp/apache-tomcat-8.0.36/lib/tomcat-websocket.jar
17:49:14.132 [main] DEBUG org.apache.catalina.startup.ClassLoaderFactory -     Including glob jar file /home/andre/dev/tmp/apache-tomcat-8.0.36/lib/catalina-ha.jar
```

The log content seems to be produced by logback, but obviously not honoring in any way logback.xml. Any suggestions?

**Comment by hazendaz** [comment] 2016-07-28 23:46
The bundle builds available on releases are drop in place to an new tomcat instance. If you take the latest 8.0.36 and drop that into a fresh tomcat build and try your same run, do your outcomes change?  I do otherwise have this running in pre-production stages at this point and it is behaving as expected.  Please note that if you used earlier versions, some of the instructions changed with newer tomcat release due to underlying changes on slf4j/logback implementations.

**Comment by hazendaz** [comment] 2016-07-29 02:38
There might be a glitch in the upload.  Some earlier changes lost a logback file in configuration.  I'll be pushing patches shortly just replacing the bad builds.

**Comment by hazendaz** [comment] 2016-07-29 03:07
Try getting the latest update, following the instructions again, and let me know if the issue persists.

**Comment by andreptb** [comment] 2016-07-29 13:45
Hi @hazendaz,

No luck. When you mention "getting latest update" you mean [here](https://github.com/grgrzybek/tomcat-slf4j-logback/releases/download/tomcat8/tomcat-juli-8.0.36-slf4j-1.7.21-logback-1.1.7.zip)? The only difference now is that an empty file *$CATALINA_HOME/logs/localhost-acess.log" is being generated.

Another problem that I forgot to mention, it seems *$CATALINA_HOME/conf/server.xml* is not correct for tomcat 8. Your version of the file is coming with *JasperListener* declared. According to [Tomcat 8 changelog](https://tomcat.apache.org/tomcat-8.0-doc/changelog.html) this listener has been removed. I had to remove the listener declaration so that Tomcat could boot properly.

**Comment by hazendaz** [comment] 2016-07-29 17:37
Thanks.  Ill take another look tonight as well as address jasper issue.  Ill start fresh so i can confirm user point of view.  Ive otherwise been doing this for so many years that i just update tomcat juli.  Obviously there have grown some pain points for new users.


Get Outlook for Android<https://aka.ms/ghei36>



On Fri, Jul 29, 2016 at 9:45 AM -0400, "André Albino Pereira" <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @hazendaz<https://github.com/hazendaz>,

No luck. When you mention "getting latest update" you mean here<https://github.com/grgrzybek/tomcat-slf4j-logback/releases/download/tomcat8/tomcat-juli-8.0.36-slf4j-1.7.21-logback-1.1.7.zip>? The only difference now is that an empty file *$CATALINA_HOME/logs/localhost-acess.log" is being generated.

Another problem that I forgot to mention, it seems $CATALINA_HOME/conf/server.xml is not correct for tomcat 8. Your version of the file is coming with JasperListener declared. According to Tomcat 8 changelog<https://tomcat.apache.org/tomcat-8.0-doc/changelog.html> this listener has been removed. I had to remove the listener declaration so that Tomcat could boot properly.

-

**Comment by andreptb** [comment] 2016-07-29 19:09
No problem @hazendaz . Take your time, if you need any help for testing just ask.

**Comment by hazendaz** [comment] 2016-07-30 20:40
I'll have to do some work to restructure the project so that all the various tomcat versions are separate.  I'm leaning towards just making it multi-module so one build builds all.  Aside from the issue you discovered, I did not experience any issues in using the project as is to apply into clean tomcat.  It worked as expected (outside of jasper issue).  The logging you provided for catalina.out doesn't adhere to the configuration being used.  If you take the zip package, brand new tomcat, unzip it directly into tomcat, fix the jasper issue in server.xml, then run it, what happens?  I did that and it just worked.

As a side note, I am preparing soon to push out tomcat 7, 8, 8.5, and 9 fully built out with metro webservices, some java EE api's, this projects logging setup, psi-probe management, and some basic configuraton beyond tomcat as 4 separate projects on my github account.  Those could serve as prime examples.  I still have work to do to ready those as I'm pruning personal info before I can upload.  If I get that up and you still haven't quite figured it out here, I'll link to the tomcat you are using so you might try that out as-is and see how to apply to your needs.

**Comment by andreptb** [comment] 2016-08-02 13:05
@hazendaz,

I'm sorry, It just doesn't work for me. Still the same behavior. I've uploaded my tomcat 've uploaded my tomcat [here](https://drive.google.com/open?id=0BwVUfHvK0ZqmRy1hMWp4WGMzZXc), maybe then you can tell what I'm doing wrong.

**Comment by hazendaz** [comment] 2016-08-05 00:25
I'm pulling your setup and will get back with you.

**Comment by hazendaz** [comment] 2016-08-13 19:05
@andreptb Delete the 'logging.properties' file.  I ran your build in git bash and eclipse.  It worked fine except it threw errors due to that file.   Removing the file, errors went away.  If you are running this out of eclipse, you will want to make sure the settings you are providing in bin (setenv) are also listed in eclipse classpath for tomcat otherwise it's not picking those up.  That appears to be part of your issue as it logged the digest which will always occur when that setup is missing in eclipse.

**Comment by hazendaz** [comment] 2016-12-09 02:34
@andreptb Any change you got it working?  I have since multi-module built the project.  I still need to address jasper and will do so prior to next release set.  Otherwise out side of my test using your build I never could repeat the issue you encountered.

**Comment by hazendaz** [comment] 2016-12-09 02:35
Added issue #123, closing this issue as no other findings currently outstanding.

**Closed by hazendaz** 2016-12-09 02:35 UTC
